package domainsearch

import (
	"fmt"
	"math/rand"
	"sync"
	"time"

	timestamppb "google.golang.org/protobuf/types/known/timestamppb"

	domainsearchv1 "github.com/olaysco/domain-search-llm/internal/gen/domainsearch/v1"
	"github.com/olaysco/domain-search-llm/internal/llm"
)

// Service implements the DomainSearchServiceServer generated by protoc.
type SearchService struct {
	domainsearchv1.UnimplementedDomainSearchServiceServer
	llmSuggester *llm.LLMSuggester

	rnd  *rand.Rand
	lock sync.Mutex
}

// NewService constructs a Service with a time-based random seed.
func NewSearchService(llmSusggester *llm.LLMSuggester) *SearchService {
	return &SearchService{
		rnd:          rand.New(rand.NewSource(time.Now().UnixNano())),
		llmSuggester: llmSusggester,
	}
}

// CheckPrice streams fake price data derived from the incoming filter.
func (s *SearchService) CheckPrice(req *domainsearchv1.SearchPricesRequest, stream domainsearchv1.DomainSearchService_CheckPriceServer) error {
	ctx := stream.Context()

	if req == nil {
		return nil
	}

	llmQuery := llm.AISuggestionRequest{
		Query:      req.Query,
		MaxResults: 10,
	}
	llmResponse, err := s.llmSuggester.GenerateDomainSuggestions(ctx, llmQuery)
	if err != nil {
		return err
	}

	fmt.Println(llmResponse)

	// for _, tld := range llmResponse {
	// 	// resp := &domainsearchv1.SearchPricesResponse{ProductId: fmt.Sprintf("%s.%s", query, tld)}

	// 	// resp.Response = &domainsearchv1.SearchPricesResponse_Price{Price: s.buildPriceData(currency, quantity)}
	// 	// if err := stream.Send(resp); err != nil {
	// 	// 	return err
	// 	// }
	// 	// time.Sleep(150 * time.Millisecond)
	// }
	return nil
}

func (s *SearchService) buildPriceData(currency string, quantity uint32) *domainsearchv1.PriceData {
	basePrice := "10.49"
	units, nanos := int64(10), int32(49000000)
	label := "hot"
	if true {
		label = "premium"
	}
	labels := []string{label}
	productPrice := &domainsearchv1.ProductPrice{
		Price: &domainsearchv1.Price{
			CurrencyCode: currency,
			Units:        units,
			Nanos:        nanos,
			Value:        fmt.Sprintf("%.2f", basePrice),
		},
		Labels: labels,
	}
	if true {
		productPrice.Promotion = &domainsearchv1.Promotion{
			Period: &domainsearchv1.PromotionPeriod{
				From: timestamppb.New(time.Now()),
				To:   timestamppb.New(time.Now().Add(30 * 24 * time.Hour)),
			},
		}
	}
	return &domainsearchv1.PriceData{
		Prices: map[string]*domainsearchv1.ProductPrice{
			"PRODUCT_CURRENCY": productPrice,
		},
	}
}
